---
apiVersion: v1
kind: Namespace
metadata:
  name: traveltap-prod
  labels:
    app : traveltap
---
apiVersion: v1
kind: Namespace
metadata:
  name: traveltap-qa
  labels:
    app : traveltap
---
apiVersion: v1
kind: Namespace
metadata:
  name: traveltap-dev
  labels:
    app : traveltap
---
apiVersion: v1
kind: Namespace
metadata:
  name: traveltap-build
  labels:
    app : traveltap
